### ISSUE TITLE
使用 npm run dev 不会弹出 nw 窗口

### ISSUE THREAD

**Issue by fengsduo** [anchengjian/anchengjian.github.io#12]
![image](https://user-images.githubusercontent.com/20245941/42794355-e0fd6d8a-89b0-11e8-8f08-e7ec3b3fc09e.png)
我的情况是，npm install -> npm run dev ->然后没有出现 nw 窗口

**Comment by anchengjian** [comment]
https://github.com/anchengjian/vue-nw-seed/issues/5 到这个 issue 下讨论吧
