### ISSUE TITLE
 Page does not exist, the content shouldn't be listed.

### ISSUE THREAD

**Issue by AmusedMe** [anchengjian/anchengjian.github.io#3]
When I enter a certain page, I delete the file name from the url, it comes an unexpected page.

Here is the screen capture:
![d2](https://cloud.githubusercontent.com/assets/19369983/19416426/88f04288-93c2-11e6-8ffd-1edcdf6bbf0c.png)

Maybe a redirect or an error page should be adopted.

**Comment by anchengjian** [comment]
thx
