### ISSUE TITLE
post目录下的md文件名前不能有‘.’

### ISSUE THREAD

**Issue by AmusedMe** [anchengjian/anchengjian.github.io#4]
在post下建立一个文件名：对package.json的理解，在测试网页中显示如下
![image](https://cloud.githubusercontent.com/assets/19369983/19511888/de0684fc-961b-11e6-82f7-dd449f512a5c.png)

测试发现，只要是.md前含有‘.’，页面中就不显示。

**Comment by anchengjian** [comment]
嗯，确认是有这个Bug，今晚回去改，谢谢。

**Comment by anchengjian** [comment]
修复了
