### ISSUE TITLE
等了一个星期，博客还没有更新

### ISSUE THREAD

**Issue by zuijiaoluo** [anchengjian/anchengjian.github.io#7]
是不是我找的地方不对，你博客更新是第一个更新到这里吗？

**Comment by anchengjian** [comment]
对，是更新到这里，你可以 `watch` 我的这个项目，然后能收到这么项目的一些最新消息，不过那样子 issue 等各种消息你都能收到，比较烦人。。  

你想看的那篇文章在这儿，几乎全贴的代码，讲解的只有一部分😂😂😂  

[https://github.com/anchengjian/anchengjian.github.io/blob/master/posts/2017/vuejs-webpack-nwjs-2.md](https://github.com/anchengjian/anchengjian.github.io/blob/master/posts/2017/vuejs-webpack-nwjs-2.md)

**Comment by zuijiaoluo** [comment]
对  这个都看完了  打算看更新的那部分呢   期待期待

**Comment by anchengjian** [comment]
蛤，又开始持续加班了，我准备清明节的时候搞那个。。

**Comment by zuijiaoluo** [comment]
程序员的😢生活，就是加班多

**Comment by zuijiaoluo** [comment]
清明等你更新
