### ISSUE TITLE
想请问一下，在linux下Build会有问题吗？

### ISSUE THREAD

**Issue by tangyue0924** [anchengjian/anchengjian.github.io#8]
好像用了很多Windows应用，会不会和linux不兼容？替换图标，安装之类的？

**Comment by anchengjian** [comment]
你说的是 [vue-nw-seed](https://github.com/anchengjian/vue-nw-seed) 这个？linux 下和mac 下我都 build 过，只需要在[配置](https://github.com/anchengjian/vue-nw-seed/blob/master/config/index.js) 中的 `builder.platforms` 去掉 `win32` 就可以了

**Comment by tangyue0924** [comment]
。。。竟然回复错地方了。。
谢谢回复啊。
我的意思是我需要在Linux环境下build win32客户端和osx64客户端，会不会有冲突~~

**Comment by anchengjian** [comment]
如果是有需要用 innoSetup build 一个安装包的话就会有冲突，不然不会冲突。可以用 `npm run build --noSetup` 来进行控制。

**Comment by tangyue0924** [comment]
好的，感谢~~
