### ISSUE TITLE
现在更新是直接下载exe 不是以前的增量更新了么？

### ISSUE THREAD

**Issue by iizhangchao** [anchengjian/anchengjian.github.io#9]

**Comment by anchengjian** [comment]
这个项目中的更新是全量更新，努力做通用的解决方案。
一是增量更新的限制比较明显，也是源于之前我在实际项目的开发中，新加一个什么驱动扩展之类的就不行了。
二是，客户端产品在打包后约在 35Mb 左右，这个大小在桌面端还是能接受的。

**Comment by anchengjian** [comment]
在 [vue-nw-seed](https://github.com/anchengjian/vue-nw-seed/issues/13) 这个地方来讨论算了
